### ISSUE TITLE
Sensor API?

### ISSUE THREAD

**Issue by ianshefferman** [redcanaryco/cbapi2#2]
Are there any plans to wrap CB 5.0's sensor API, specifically to programmatically replicate some of the things one can do with the new Go Live feature?

https://github.com/carbonblack/cbapi/tree/master/sensor_apis

**Comment by jgarman** [comment]
We aren't planning on doing the work ourselves as I've been focusing on implementing the full complement of client REST APIs. That said I'm not opposed to having that in the tree - I'm happy to review code/patches as long as the implementation fits the guidelines and spirit that I've established in the readme - continuing the work of creating the most efficient and intuitive Carbon Black API available.
